/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queuepalinlist;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;
import java.util.Stack;

/**
 *
 * @author carmitnaor
 */
public class QueuePalinlist extends javax.swing.JFrame {

    /**
     * Creates new form QueuePalinlist2
     */
    Stack<String> s= new Stack<>();
    Queue<String> q = new LinkedList<>();
    ArrayList<String> TestCases = new ArrayList<>(Arrays.asList("one two three two one",
                                                                  "1 2 3 4 5 one two three four five",
                                                                  "a b c d e f g x y z g f h",
                                                                  "racecar is racecar",
                                                                  "1 2 3 a b c c b a 3 2 1",
                                                                  "chicken is a chicken"));


    public QueuePalinlist() {
        initComponents();
        for(int i = 0; i<TestCases.size(); i++){
            loadStackAndQueue(i);
            System.out.println(s);
            if(isPalinlist(i))
            { 
                System.out.print(isPalinlist(i) );
                System.out.print(" is a palinlist. \n");
            }
            else{
                System.out.print(isPalinlist(i) );
                System.out.print(" is not a palinlist. \n");
            }
        }
        
    }
    public boolean isPalinlist(int indexTestCase){
        
        Scanner scan =new Scanner(TestCases.get(indexTestCase));
        int i = 0;
         while(scan.hasNext()){
             scan.next();
             i++;
         }
         Scanner scan2 = new Scanner(TestCases.get(indexTestCase));
         
            int SizeRun = i/2;

             for(int loop1 = 0; loop1 < SizeRun; loop1++){
                if(q.peek().equals(s.peek())) {
                 
                     q.remove();
                     s.pop();
                }
                else{
                    return false; 
                }
                        
             }
             return true; 
             
            
         
        
         
         
    
        
        
    }
    public void loadStackAndQueue(int indexTestCase){
        Scanner scan =new Scanner(TestCases.get(indexTestCase));
        while(!q.isEmpty())
        {
            q.remove();
        }
        while(!s.isEmpty())
        {
            s.pop();
        }
        while(scan.hasNext()){
            String currentChar = scan.next();
            s.push(currentChar);
            q.add(currentChar);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueuePalinlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueuePalinlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueuePalinlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueuePalinlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueuePalinlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
